apiVersion: v1
kind: Service
metadata:
  name: ok5511
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ok5511"
    port: 8080
  selector:
    app: ok5511
